teacherdirectory/teacher/urls.py
from django.urls import path, include
from teacher import views

urlpatterns = [
    path('t_list', views.teacher_list,name='teacher_list'),
    path('', views.index,name='home'),
    path('import', views.import_data,name='import'),
    path('simple_upload', views.simple_upload,name='simple_upload'),
    path('/details/<int:pk>', views.teacher_detail,name='details'),
    #path('update_detail/<int:id>', views.update_detail,name='update_detail'),
]

app_name = 'teacher'

teacherdirectory/teacherdirectory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from user import views as user_view
from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teacher.urls', namespace='teacher')),

    path('',include("user.urls")),
    path('accounts/',include('django.contrib.auth.urls'))
    
    # path('', include('user.urls')),
    # path('login/', user_view.Login, name ='login'),
    # path('logout/', auth.LogoutView.as_view(template_name ='user/index.html'), name ='logout'),
    # path('register/', user_view.register, name ='register'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacherdirectory/user/urls.py
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'user'


urlpatterns = [
    path('home',views.index,name="home"),
    path('user/sign_up/',views.sign_up,name="sign-up")
]

teacherdirectory/teacher/models.py
from django.db import models
from django.contrib.auth.models import User


class Teacher(models.Model):
    first_name=models.CharField(max_length=56)
    last_name=models.CharField(max_length=56)
    email_address=models.EmailField()
    profile_picture = models.ImageField(default='default.jpg',upload_to='teacher')
    mobile_number=models.CharField(max_length=16)
    room_number = models.CharField(max_length=10)
    subject_taught = models.CharField(max_length=256)
    # subject_count= models.PositiveIntegerField()
    created = models.DateField(auto_now_add=True)
    
    class Meta:
        ordering=('-created',)

    def __str__(self):
        return self.first_name


       

teacherdirectory/user/models.py
from django.db import models

# Create your models here.

teacherdirectory/teacher/views.py
from django.shortcuts import render

from django.db.models import Q
from django.core.paginator import EmptyPage,Paginator,PageNotAnInteger
from django.shortcuts import render,get_object_or_404,redirect
from teacher.models import Teacher
from django.contrib.auth.models import User
from django.contrib import messages
import datetime
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect,JsonResponse,Http404, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import io,csv

# Create your views here.
def index(request):
    return render(request, 'index.html')

def teacher_list(request):
    t_list = Teacher.objects.all()
    paginator=Paginator(t_list, 5)
    page_number=request.GET.get('page')
    query=request.GET.get("q")
    if query:
        t_list=t_list.filter(Q(last_name__icontains=query) | Q(subject_taught__icontains=query)).distinct()   
    try:
        t_list=paginator.page(page_number)
    except PageNotAnInteger:
        t_list=paginator.page(1)
    except EmptyPage:
        t_list=paginator.page(paginator.num_pages)
    return render(request, 'teacher_list.html', {'t_list':t_list,})


def teacher_detail(request,pk):
    t_obj = Teacher.objects.get(id=pk)
    return render(request, 'details.html', {'t_obj':t_obj,})   


from tablib import Dataset
from .resources import PersonResource

# @login_required
# def simple_upload(request):
#     if request.method == 'POST':
#         person_resource = PersonResource()
#         dataset = Dataset()
#         new_persons = request.FILES['myfile']
        
#         imported_data = Dataset().load(new_persons.read().decode('utf-8'), format='csv', headers=False)
#         print(imported_data)

#         #imported_data = dataset.load(new_persons.read())
#         result = person_resource.import_data(dataset, dry_run=True)  # Test the data import
#         print(result)

#         if not result.has_errors():
#             person_resource.import_data(dataset, dry_run=False)  # Actually import now
#             print(person_resource)

#     return render(request, 'index.html')

@login_required
def import_data(request):
    return render(request, "import.html")   


def simple_upload(request):
    user = request.user #get the current login user details
    paramFile = io.TextIOWrapper(request.FILES['myfile'].file)
    portfolio1 = csv.DictReader(paramFile)
    list_of_dict = list(portfolio1)
    print(list_of_dict)
    objs = [ Teacher(
            first_name=row['First Name'],
            last_name=row['Last Name'],
            email_address=row['Email Address'],
            profile_picture=row['Profile picture'],
            mobile_number=row['Phone Number'],
            room_number=row['Room Number'],
            subject_taught=row['Subjects taught'],
           # created_by=user, #This is foreignkey value
           
        )
        for row in list_of_dict
        ]
    try:
        msg = Teacher.objects.bulk_create(objs)
        returnmsg = {"status_code": 200}
        print('imported successfully')
        return render(request, 'index.html')
    except Exception as e:
        print('Error While Importing Data: ',e)
        returnmsg = {"status_code": 500}
       
    #return JsonResponse(returnmsg)
    return render(request, 'import.html')    

teacherdirectory/user/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    return render(request,'registration/index.html')
    
def sign_up(request):
    context = {}
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            login(request,user)
            return render(request,'registration/index.html')
    context['form']=form
    return render(request,'registration/sign_up.html',context)

teacherdirectory/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Teacher Directory</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %} " rel="stylesheet">


  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{%static "css/one-page-wonder.min.css" %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Home</a>
      <a class="navbar-brand" href="/t_list">Teachers</a>
      <a class="navbar-brand" href="import">Import</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
           <a class="nav-link" > {{request.user|title}}</a>
         </li>   
         <li class="nav-item">
            <a class="nav-link" href="accounts/logout">Logout</a>
          </li>   
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="user/sign_up/">Sign Up</a>
          </li>
         {% endif %}
        </ul>
      </div>
    </div>
  </nav>


  
    {% block container_block %}


  {% endblock %}
	

  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2021</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{%static "vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js"%}"></script>

</body>

</html>

teacherdirectory/templates/details.html
{% extends 'base.html'%}

{% load static%}

    <!-- Main Content -->
{% block container_block %}


<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="{% static "css/details.css "%}" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<h1> Details </h1>

<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                    
                            <img src="{{ t_obj.profile_picture.url }}" class="img-responsive"  alt=""/>
                            {% comment %} <div class="file btn btn-lg btn-primary">
                                Change Photo
                                <input type="file" name="file"/>
                            </div> {% endcomment %}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        {{t_obj.first_name}} {{t_obj.last_name}}
                                    </h5>
                                    <h6>
                                        Teacher 
                                    </h6>
                                    <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                {% comment %} <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                                </li> {% endcomment %}
                            </ul>
                        </div>
                    </div>
                    {% comment %} <div class="col-md-2">
                        <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/>
                    </div> {% endcomment %}
                    <div class="col-md-2">
                     <a class="profile-edit-btn" href="/">Back</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>WORK LINK</p>
                            Teacher<br/>
                            
                            <p>SKILLS</p>
                            Good knowlodge of Subject<br/>
                             {{t_obj.subject_taught}} 
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>User Id</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{t_obj.id}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{t_obj.first_name}} {{t_obj.last_name}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{t_obj.email_address}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Phone</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{t_obj.mobile_number}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Profession</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Teacher</p>
                                            </div>
                                        </div>

                                         <div class="row">
                                            <div class="col-md-6">
                                                <label>Subject Taught</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{t_obj.subject_taught}}</p>
                                            </div>
                                        </div>
                            </div>
                            {% comment %} <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Experience</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Expert</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Hourly Rate</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>10$/hr</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Total Projects</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>230</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>English Level</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Expert</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Availability</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>6 months</p>
                                            </div>
                                        </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Your Bio</label><br/>
                                        <p>Your detail description</p>
                                    </div>
                                </div> {% endcomment %}
                            </div>
                        </div>
                    </div>
                </div>
            </form>           
        </div>


        {% endblock %}

teacherdirectory/templates/import.html
<h1> Import data from here....</h1>

<div>
  <form method="post" action="simple_upload" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
</div>

teacherdirectory/templates/index.html
{% extends 'base.html'%}

{% load static%}

    <!-- Main Content -->
{% block container_block %}



  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">The more that you read</h1>
        <h2 class="masthead-subheading mb-0">the more things you will know</h2>
        <a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">Read More</a>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>


{% endblock %}

teacherdirectory/templates/pagination.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
     {% comment %} <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">  {% endcomment %}

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav aria-label="Page navigation example">
    <center>
  <ul class="pagination justify-content-center">
    <li class="page-item ">
      {% if page.has_previous%}
      <a class="page-link" href="?page={{page.previous_page_number}}" tabindex="-1">Previous</a>
      {% endif %}
    </li>
    <li class="page-item"><a class="page-link" href="{{page.number}} of {{page.paginator.num_pages}}">{{page.number}}</a></li>

    <li class="page-item">
        {% if page.has_next%}
      <a class="page-link" href="?page={{page.next_page_number}}">Next</a>
      {% endif %}
    </li>
  </ul>
  </center>
</nav>
  </body>
</html>

teacherdirectory/templates/teacher_list.html
{% extends 'base.html'%}

{% load static%}

    <!-- Main Content -->
{% block container_block %}



<header class="masthead text-center text-white">
   
 <!-- On rows -->
<div class="table-responsive">

<table class="table table-hover">
  <thead>
    <tr class="table-primary">
      <th scope="col">ID.</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Mobile</th>
      <th scope="col">Subject</th>
    <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <h1> List of Teachers </h1>
   <nav class="navbar navbar-light bg-light">
  <form class="example"  method="GET" action="" >
          <input type="text" placeholder="Search.." name="q" value="{{request.GET.q}}" >
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>
  {% for teacher in t_list %}
     
    <tr class="table-primary">
      <th scope="row">{{teacher.id}}</th>
      <td>{{teacher.first_name}}</td>
      <td>{{teacher.last_name}}</td>
      <td>{{teacher.mobile_number}}</td>
      <td>{{teacher.subject_taught}}</td>
      <td><a href="{% url 'teacher:details'  pk=teacher.id %}"> <button type="button" class="btn btn-info">Teacher Info</button> </a> </td>
    </tr>

    {% endfor %}
    
   
  </tbody>
</table>
</div>
{%include 'pagination.html' with page=t_list %} 
  </header>


{% endblock %}

teacherdirectory/templates/update_detail.html
{% extends 'base.html'%}

{% load static%}

<link href="{% static "css/update.css "%}" rel="stylesheet" id="bootstrap-css">
    <!-- Main Content -->
{% block container_block %}

<div class="container rounded bg-white mt-5">
    <div class="row">
        <div class="col-md-4 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" src="https://i.imgur.com/0eg0aG0.jpg" width="90"><span class="font-weight-bold">John Doe</span><span class="text-black-50">john_doe12@bbb.com</span><span>United States</span></div>
        </div>
        <div class="col-md-8">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <div class="d-flex flex-row align-items-center back"><i class="fa fa-long-arrow-left mr-1 mb-1"></i>
                        <h6>Back to home</h6>
                    </div>
                    <h6 class="text-right">Edit Profile</h6>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><input type="text" class="form-control" placeholder="first name" value="John"></div>
                    <div class="col-md-6"><input type="text" class="form-control" value="Doe" placeholder="Doe"></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6"><input type="text" class="form-control" placeholder="Email" value="john_doe12@bbb.com"></div>
                    <div class="col-md-6"><input type="text" class="form-control" value="+19685969668" placeholder="Phone number"></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6"><input type="text" class="form-control" placeholder="address" value="D-113, right avenue block, CA,USA"></div>
                    <div class="col-md-6"><input type="text" class="form-control" value="USA" placeholder="Country"></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6"><input type="text" class="form-control" placeholder="Bank Name" value="Bank of America"></div>
                    <div class="col-md-6"><input type="text" class="form-control" value="043958409584095" placeholder="Account Number"></div>
                </div>
                <div class="mt-5 text-right"><button class="btn btn-primary profile-button" type="button">Save Profile</button></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}